# Site settings
title: 
header-img: img/home-bg.png
email: palacios.joshua@gmail.com
copyright_name: jshwa
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jshwa
learn_profile: jshwa
email_username: palacios.joshua@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
remote_theme: hmfaysal/Notepad
